package flow;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2019-JUL-03  04:02:45 PM
 */
public class SetLangFromDTMF extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2019-JUL-03  04:02:45 PM
	 */
	public SetLangFromDTMF() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2019-AUG-28  10:11:10 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2019-AUG-28  10:11:10 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2019-AUG-28  10:11:10 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "WelcomeAll:value", com.avaya.sce.runtime.Expression.INT_EQUAL, "2", false).setDebugId(39)).evaluate(mySession)) {
			actions = new java.util.ArrayList(3);
			actions.add(new com.avaya.sce.runtime.varoperations.SetCurrentLanguage("english", true).setDebugId(49));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("SelectedLanguage", "2", true).setDebugId(190));
			actions.add(new com.avaya.sce.runtime.Next("SelectAll", "English").setDebugId(37));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "WelcomeAll:value", com.avaya.sce.runtime.Expression.INT_EQUAL, "3", false).setDebugId(40)).evaluate(mySession)) {
			actions = new java.util.ArrayList(3);
			actions.add(new com.avaya.sce.runtime.varoperations.SetCurrentLanguage("France", true).setDebugId(50));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("SelectedLanguage", "3", true).setDebugId(191));
			actions.add(new com.avaya.sce.runtime.Next("SelectAll", "French").setDebugId(41));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition3", "WelcomeAll:value", com.avaya.sce.runtime.Expression.INT_EQUAL, "4", false).setDebugId(42)).evaluate(mySession)) {
			actions = new java.util.ArrayList(3);
			actions.add(new com.avaya.sce.runtime.varoperations.SetCurrentLanguage("Germany", true).setDebugId(51));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("SelectedLanguage", "4", true).setDebugId(192));
			actions.add(new com.avaya.sce.runtime.Next("SelectAll", "German").setDebugId(43));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition4", "WelcomeAll:value", com.avaya.sce.runtime.Expression.INT_EQUAL, "5", false).setDebugId(44)).evaluate(mySession)) {
			actions = new java.util.ArrayList(3);
			actions.add(new com.avaya.sce.runtime.varoperations.SetCurrentLanguage("Spanish", true).setDebugId(52));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("SelectedLanguage", "5", true).setDebugId(193));
			actions.add(new com.avaya.sce.runtime.Next("SelectAll", "Spanish").setDebugId(45));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.Next("WelcomeAll", "Else").setDebugId(47));
			actions.add(new com.avaya.sce.runtime.varoperations.SetCurrentLanguage("Spanish", true).setDebugId(53));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
